name: Test Folder chagnes
on:
  workflow_dispatch: 
  push:
    branches:
      - main   
jobs:
  changes:
    name: Detect paths changes
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Determine which paths have changed
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: csv
          base: ${{ github.ref }}
          filters: |
            core:
              - 'oci/core/**' 
            data:
              - 'oci/data/**'
    
      - name: Extract directories
        if: ${{ steps.filter.outputs.data == 'true' }}
        env:
          list_of_files: ${{ steps.filter.outputs.data_files }} 
        id: extract
        run: |
          IFS=',' read -ra file_paths <<< "$list_of_files"
          directories=()
          for path in "${file_paths[@]}"; do
            directory=$(dirname "$path")
            if [[ ! " ${directories[@]} " =~ " ${directory} " ]]; then
              directories+=("$directory")
            fi
          done
          echo "directories=${directories[*]}" >> $GITHUB_ENV
      - name: Run terraform
        env: 
          directories: ${{ env.directories }}
        run: |
          pwd
          for directory in $directories
          do
            pwd
            ls -l
            echo $directory
            cd $directory
            ls -l
          done
        