name: Test Folder chagnes
on:
  workflow_dispatch: 
  push:
    branches:
      - main
    
jobs:
  changes:
    name: Detect paths changes
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Determine which paths have changed
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: csv
          base: ${{ github.ref }}
          filters: |
            core:
              - 'oci/core/**' 
            data:
              - 'oci/data/**'
    outputs:
      core: ${{ steps.filter.outputs.core }}
      data: ${{ steps.filter.outputs.data }}
      data_files: ${{ steps.filter.outputs.data_files}}      
  
  usechanges:
    runs-on: ubuntu-latest
    needs: changes
    steps:    
      - name: List changed files
        env:
          is_changed: ${{ needs.changes.outputs.data}}
          changed_files: ${{ needs.changes.outputs.data_files }}
        run: 
          echo "${{ env.is_changed }}"
          folder_names=$(cut -d ',' -f 1 "$changed_files" | awk -F '/' '{print $1}' | sort | uniq)
          echo $folder_names
          folder_array=()
          while IFS= read -r folder; do
              folder_array+=("$folder")
          done <<< "$folder_names"
          echo "Unique folders:"
          for folder in "${folder_array[@]}"; do
              echo "$folder"
          done
          
        
            

