name: Testing

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: update env
        env:
          vars: ${{ vars.ENV_VARS }}
        run: |
            echo $vars | base64 -d  > varfile.txt
            cat varfile.txt
            
            echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
            while read line 
            do                
              echo $line
              varname=$(echo $line | cut -d "=" -f2)
              echo "::add-mask::$varname"
              echo $line >> $GITHUB_ENV
            done< varfile.txt
            
            
      - name: check masking
        run: |
          somevar=${{ vars.ENV_VARS }}
          echo '::add-mask::$somevar'
          echo $somevar


